apiVersion: v1
kind: Service
metadata:
  name: rcabench
  labels:
    app: rcabench
spec:
  type: ClusterIP
  selector:
    app: rcabench
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
