apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rcabench-ingress
  annotations:
    # Optionally add additional annotations for your ingress controller here
spec:
  ingressClassName: haproxy
  rules:
    - host: rcabench.nrp-nautilus.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: rcabench
                port:
                  number: 80
  # To enable TLS, uncomment and configure the tls section and add the secret
  tls:
    - hosts:
        - rcabench.nrp-nautilus.io
      secretName: rcabench-tls
