[core]
workspace_base = "" # Will be set programmatically
cache_dir = ""
file_store_path = ""
save_trajectory_path = ""
run_as_openhands = false

[llm]
model = "" # Will be set programmatically
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "docker.openhands.dev/openhands/runtime:0.62-nikolaik"
docker_runtime_kwargs = {auto_remove = true}  # Change to false for debugging
runtime_binding_address = "127.0.0.1"